<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>WindowsBootSwitcher.Service</RootNamespace>
    <!-- Can't do this until https://github.com/dotnet/runtime/issues/61960 gets fixed-->
    <!-- <PublishAot>true</PublishAot> -->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.0" />
    <ProjectReference Include="..\WindowsBootSwitcher.Contracts\WindowsBootSwitcher.Contracts.csproj" />
    <PackageReference Include="System.Management" Version="10.0.0" />
  </ItemGroup>
</Project>
